### ISSUE TITLE
Option to add hashes to config-map and secret names

### ISSUE THREAD

**Issue by maybedino** [cdk8s-team/cdk8s-plus#1288]
Kustomize has a feature where if you create a config-map (or a secret), a hash of the config-map will be added to the name. If you change a config-map, the name will change and Kubernetes will re-create all workloads that are using this config-map with the new one mounted. This has some advantages:
- Old instances of workload which might not be compatible with the new config-map will keep using the old one.
- Rollbacks of deployments will also roll back the config-map.
- Sometimes config-maps are not reloaded, for example if you use subPath. This will prevent this.
- If whatever you are running does not detect config file changes, this will force a restart.

Right now this not that easy to do, the name is created before the data because it uses lazy. Maybe this would be a useful feature to add to cdk8s-plus ConfigMap and Secret constructs as an option?

**Comment by iliapolo** [comment]
@maybedino can you elaborate on these bullets please? How does this achieve them? 

> - Old instances of workload which might not be compatible with the new config-map will keep using the old one.
> - Rollbacks of deployments will also roll back the config-map.

**Comment by maybedino** [comment]
Let's say you roll out an updated deployment, but the new one uses a config file that is not backwards-compatible. If you update your config map, Kubernetes will reload config maps mounted to old version of the deployment. Same for rollbacks, if you roll back your deployment, it keeps using the new config map. 

So usually what you would do is create versions, call it my-config-map-v2 and update the config map name in the volume. But you have to do this manually every time. Adding a hash to the name just does this automatically whenever the contend of the config map changes. It makes the content part of the deployment specification, similar to if you set your config via environment variables.

I think the main use-case for this to automatically trigger roll-outs when a config file changes. But it's also useful in some other situations.
