### ISSUE TITLE
Omit defaults for SecurityContext

### ISSUE THREAD

**Issue by 7oku** [cdk8s-team/cdk8s-plus#1339]
According to k8s [docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#securitycontext-v1-core) the `runAsUser` field is taken from the image metadata if omitted. 

cdk8splus24(golang) however does set the security context for pod and container with default values: 
```bash
[...]
securityContext:
  allowPrivilegeEscalation: false
  privileged: false
  readOnlyRootFilesystem: true
  runAsGroup: 26000
  runAsNonRoot: true
  runAsUser: 25000
[...]
```

without explicitly specifying a security context using code like this:
```golang
dep.AddContainer(&cdk8splus24.ContainerProps{
		Name:  jsii.String(name),
		Image: jsii.String(*image),
		Ports: &containerports,
	})
```
Although I like following best practices in regards of security by default setting good value of >1000 for `runAsUser`, this breaks images.
While we can set for instance `readOnlyRootFileystem: false`, we can set `runAsUser` only to an int value. Omitting it results in cdk8s+ setting the default of 25000, so no way to have kubernetes pick the UID from a docker image with cdk8s generated manifests.

Is there any way to avoid having `runAsUser` to be added to the manifests at all?

**Comment by iliapolo** [comment]
@7oku Can you elaborate on how exactly this breaks images? can you share the error and the specific image?

**Comment by 7oku** [comment]
@iliapolo I don't have a specific error messages present any more.

We cannot deploy or run any image based on the official [nginx image](https://hub.docker.com/_/nginx). cdk8s(plus) hardly overwrites the `runAsUser` field with an uid of 25000, but the image defaults to and relies on using uid 101 to drop privileges. Any cdk8s(plus) synthed manifests will break permissions in the image completely, because the uid has been changed. 

k8s default behaviour is to determine the uid from the Dockerfile (or the uid metadata in the resulting image). To leverage this default k8s behaviour we need the possibility to have a blank `runAsUser` section.

**Comment by iliapolo** [comment]
@7oku Thanks. I can confirm that nginx images wont start with 25000 as the UID. 

```console
❯ docker run -u 25000 -it nginx                                                                                                                                                                                                                                                                                 [17:32:12]
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/11/23 15:32:12 [warn] 1#1: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
2022/11/23 15:32:12 [emerg] 1#1: mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
nginx: [emerg] mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
```

Created a PR to revert these defaults while we investigate and come up with a better mechanism. 

THanks!
