### ISSUE TITLE
Support for terminationGracePeriodSeconds

### ISSUE THREAD

**Issue by ibarrick** [cdk8s-team/cdk8s-plus#1413]
Is it on the roadmap to add support for this field on Deployments?

**Comment by iliapolo** [comment]
@ibarrick Its not on the Roadmap just yet but we will gladly accept a PR. If we see this issue getting more upvotes we will reconsider putting it on the roadmap.

**Comment by galsasi1989** [comment]
Hi @iliapolo 
Here's a PR: https://github.com/cdk8s-team/cdk8s-plus/pull/2026
