### ISSUE TITLE
Deployment doesn't accept Container objects

### ISSUE THREAD

**Issue by yfried** [cdk8s-team/cdk8s-plus#1508]
Hi
I'm following this [doc](https://pypi.org/project/cdk8s-plus/) and trying to use `Container.mount()`

The problem is that the `Deployment.containters` expects `ContainerProps`, but `ContainerProps` doesn't have `mount` method.

The only way to use the mount method is by getting the container object from `Deployment.containers` after the deployment is created.

So the given example doesn't work
```python
container = kplus.Container(
    image="node:14.4.0-alpine3.12",
    command=["node", "index.js", f"{port}"],
    port=port,
)

container.mount(app_path, app_volume)
deployment = kplus.Deployment(chart, "Deployment",
    replicas=3,
    containers=[container]
)

``` 
Results with 
```
TypeError: type of argument containers must be one of (Sequence[Union[cdk8s_plus_25.ContainerProps, Dict[str, Any]]], NoneType); got list instead
```

The way to do this is
```python
container_p = kplus.ContainerProps(
    image="node:14.4.0-alpine3.12",
    command=["node", "index.js", f"{port}"],
    port=port,
)

deployment = kplus.Deployment(chart, "Deployment",
    replicas=3,
    containers=[container_p]
)

container = deployment.containers[0]
container.mount(app_path, app_volume)
```

This would be easier if Deployment would accept Container, or if Container had a `.props` property to convert it

**Comment by iliapolo** [comment]
@yfried Thanks. Indeed the example in the doc is outdated. We will fix it. 

You can also do the following, which is a bit more ergonomic IMO:

```python
deployment = kplus.Deployment(chart, "Deployment")
container = deployment.add_container(
    image="node:14.4.0-alpine3.12",
    command=["node", "index.js", f"{port}"],
    port=port)
container.mount(app_path, app_volume)
```

**Comment by yfried** [comment]
@iliapolo tnx.
Fixing the doc is important, but is there a way to reduce the mixup between `Container` and `ContainerProps` objects?
Your suggestion hides the fact the a simple re-arrangement of the code would break it.

Also - this becomes a bit harder to implement if we want to define the container in a different module for reusing it.

**Comment by iliapolo** [comment]
@yfried 

> Your suggestion hides the fact the a simple re-arrangement of the code would break it.

How do you mean? What re-arrangement would break it? 

> Also - this becomes a bit harder to implement if we want to define the container in a different module for reusing it.

You're looking to share a mounted container right? not just its props?

**Comment by yfried** [comment]
@iliapolo 
in this instance yes.

Having to juggle Container and ContainerProps seems to block some on the intended simplification behind cdk. I think.

**Comment by iliapolo** [comment]
@yfried Yeah I see what you mean. Actually in an earlier version of the API the `Deployment` resource did in fact accept a `Container`, and not `ContainerProps`.

I think adding a `.props` to the `Container` class so it can be reused is reasonable. Would you be interested in working on this after we hash it out together? 

Another option I was thinking about is something like this:

```ts
const container = new kplus.Container(containerProps);
const deployment = container.deploy(deploymentPropsMinusContainerProps);
```

But that seems a higher level feature we can always add at some point.

**Comment by yfried** [comment]
> @yfried Yeah I see what you mean. Actually in an earlier version of the API the `Deployment` resource did in fact accept a `Container`, and not `ContainerProps`.
> 
> I think adding a `.props` to the `Container` class so it can be reused is reasonable. Would you be interested in working on this after we hash it out together?

I can try. With a little guidance

**Comment by iliapolo** [comment]
@yfried Cool. Let me ponder on this a bit and get back to you.

**Comment by iliapolo** [comment]
@yfried I'm still hesitant about adding `.props` honestly since there's a larger pattern in question here.

How about we just add an `attachContainer` method that will accept a container? Basically just add it [here](https://github.com/cdk8s-team/cdk8s-plus/blob/k8s-25/main/src/pod.ts#L113). Wanna pick it up? Should be straight forward.
