### ISSUE TITLE
Allow to jsonPatch containers

### ISSUE THREAD

**Issue by yfried** [cdk8s-team/cdk8s-plus#1534]
Hi,
Currently, can't patch container objects
```python
my_container = my_deployment.add_container(kplus.ContainerProps(...))
kubeContainer = cdk8s.ApiObject.of(my_container)
```
Gets
```
Expected type 'IConstruct', got 'Container' instead
```

The current solution is to patch the deployment instead but:

1. This is easy when I have a single container. but patching a container in a list is a lot harder
2. This means that I can’t reuse the patched container.

Thank you

**Comment by iliapolo** [comment]
Effort large because I still don't really know how to implement this, but its a nice feature to have.
