### ISSUE TITLE
Publish cdk8s-plus-23 and deprecate cdk8s-plus-20

### ISSUE THREAD

**Issue by Chriscbr** [cdk8s-team/cdk8s-plus#193]
Currently our plan is to support the three latest versions of kubernetes. Since Kubernetes 1.23 has been released (https://kubernetes.io/blog/2021/12/07/kubernetes-1-23-release-announcement/) we should update the supported libraries accordingly.

**Comment by iliapolo** [comment]
Released: https://constructs.dev/packages/cdk8s-plus-23
