### ISSUE TITLE
Kubevirt

### ISSUE THREAD

**Issue by unicomp21** [cdk8s-team/cdk8s-plus#216]
Sorry for asking a question here, but discussions aren't enabled.  Can we start another repo/project for kubevirt?

https://kubevirt.io/user-guide/virtual_machines/replicaset/

**Comment by Chriscbr** [comment]
Yes, you're welcome to create a library with cdk8s constructs and publish it to NPM, and then it will be listed among other [cdk8s libraries on constructs.dev](https://constructs.dev/search?cdk=cdk8s&offset=0).

We haven't written a guide for this yet, but to publish your cdk8s library it just needs to be compiled using JSII (https://aws.github.io/jsii/). Looking at another cdk8s community construct library might be a good starting point on how to set this up.

**Comment by unicomp21** [comment]
thx
