### ISSUE TITLE
Container resource requirements and HPA

### ISSUE THREAD

**Issue by foriequal0** [cdk8s-team/cdk8s-plus#27]
### Description of the feature or enhancement:
Containers can set their resource limits/requests.

### Use Case:
Horizontal Pod Autoscaler requirs containers to set resource requirements. 

### Proposed Solution:
```ts
const container = deployment.addContainer({
 resources: {
   cpu: {
     request: Cpu.millis(100),
     limit: Cpu.units(0.5),
   }
 }
});
container.resources.memory.request = Size.mebibytes(100);
container.resources.memory.limit = Size.gibibytes(1);
// optional? 
container.resources.setHugepage("2Mi", {
  ...
})
```

### Other:
* [x] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by akefirad** [comment]
Any update here? Thanks.

**Comment by iliapolo** [comment]
@akefirad We are not currently working on this. Would you be interested in contributing?

**Comment by akefirad** [comment]
Sure, but I would probably need help, since I'm not familiar with the internal of the library.

**Comment by iliapolo** [comment]
You'll want to start with adding the `resources` property to the container interface [here](https://github.com/cdk8s-team/cdk8s-plus/blob/k8s-22/main/src/container.ts#L149) and just look at how other properties are propagated onwards. 

Hopefully the relevant code is clear enough, but let us know if you have some specific questions. 

Thanks!
