### ISSUE TITLE
Enhanced port

### ISSUE THREAD

**Issue by foriequal0** [cdk8s-team/cdk8s-plus#28]
### Description of the feature or enhancement:
Current containers can only export a single port. It has even limited set of features, no named port, cannot set protocols.

### Proposed Solution:
```ts
const deployment = new Deployment(...);
const container = deployment.addContainer({
  ...
  ports: [
    { name: "http", containerPort: 80, }
  ]
});

const httpPort = container.getPort("http"); // == container.getPort(80);
const webhookPort = container.addPort(8080, { name: "webhook" });

deployment.expose(80, {
  targetPort: httpPort,
});
deployment.expose(8080, {
  targetPort: "webhook",
});

```

`deployment.expose()` also should validate given `targetPort` is actually owned by any of its child containers.
Also it would be better to warn/error for shadowed ports (proactively at the time of `addPort`, or reactively at the time of `expose`) since Kubernetes doesn't validate uniqueness of ports/names in a pod (https://github.com/kubernetes/kubernetes/issues/54213)

### Other:

* [x] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rohitranjan1991** [comment]
@iliapolo any update on this ?? Need this badly

**Comment by rohitranjan1991** [comment]
@iliapolo @Chriscbr any update on this ? :-|

**Comment by iliapolo** [comment]
@rohitranjan1991 we currently don't have plans to implement this. Are you able to escape hatch your way out it? We would also accept a contribution here

**Comment by rohitranjan1991** [comment]
@iliapolo Nope, I haven't been able to find my way around this. Still looking

**Comment by JustinPlute** [comment]
@iliapolo, why don't you have plans to implement? can this get re-opened?

**Comment by oura-kataja** [comment]
@iliapolo please reconsider implementing this. Exposing multiple ports has valid use cases, for example we want to have Prometheus metrics scraping endpoint on a different port.

**Comment by iliapolo** [comment]
Reopening this due to popular demand :) 

We will prioritize this soon, stay tuned.

**Comment by cchubb-silvertree** [comment]
Please also be sure to support protocol: TCP or UDP as well.

**Comment by awlsring** [comment]
I have a working example of using escape hatches to do this. Figured I'd share this even though the feature should be soon-ish.

```typescript
// CDK8S+ Deployment stuff. Don't declare port in here
const deployment = new Deployment(this, "deployment", {...})

// ApiObject for Escape Hatch
const d = ApiObject.of(deployment)

// Create the empty port list
d.addJsonPatch(JsonPatch.add("/spec/template/spec/containers/0/ports", []))

// Adding port 80 as http
d.addJsonPatch(JsonPatch.replace("/spec/template/spec/containers/0/ports/0", {
  "name": "http",
  "containerPort": 80
}))
// Adding port 443 as https
d.addJsonPatch(JsonPatch.add("/spec/template/spec/containers/0/ports/1", {
  "name": "https",
  "containerPort": 443
}))
```

Outputs
```yaml
...
containers:
    ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
...
```
