### ISSUE TITLE
Set resources (requests and limits) for containers

### ISSUE THREAD

**Issue by Alon-Katz** [cdk8s-team/cdk8s-plus#307]
Hi, cdk8s+ is a great library but its missing a basic but a very important feature of setting the resources of the container.

I could not find any reference for it in the documentation, but I did find the option [Escape Hatches](https://cdk8s.io/docs/latest/concepts/escape-hatches/). This worked great for me when adding nodeSelector, but it does not seem to work with the resources key.

This is the code I tried:
```
        deployment = Deployment(....)
        kube_deployment = ApiObject.of(deployment)
        kube_deployment.add_json_patch(
            JsonPatch.add("/spec/template/spec/containers/0/resources", {
                "requests": {"cpu": "100m", "memory": "0.2Gi"},
                "limits": {"cpu": "200m", "memory": "0.5Gi"},
            })
        )
```
When I look at the output json, it does seem to add the resources key and even the limits and requests, but no matter what I tried it keeps adding them with an empty dict inside. This is what is added to the json:
`'resources': {'limits': {}, 'requests': {}}`

Is there a way to make this work?
Thanks!

**Comment by Chriscbr** [comment]
Not sure but I think the issue might be related to this bug: https://github.com/cdk8s-team/cdk8s/issues/2172

**Comment by Alon-Katz** [comment]
Looks like it is related, hopefully your idea of how to fix it will soon be applied :)

**Comment by iliapolo** [comment]
@Alon-Katz this was implemented in https://github.com/cdk8s-team/cdk8s-plus/pull/390/files and now available:

https://constructs.dev/packages/cdk8s-plus-24/v/2.0.0-rc.13/api/Container?lang=typescript#property.resources

Resolving.
