### ISSUE TITLE
Add support for affinity rules in pods and deployments

### ISSUE THREAD

**Issue by kesavkolla** [cdk8s-team/cdk8s-plus#31]
Please allow support to add affinity for deployment template specification.

**Comment by philschmid** [comment]
Is there an update on this?

**Comment by iliapolo** [comment]
Hi @philschmid - this isn't currently planned. We will gladly accept a PR though :)

In the meantime you can use [Escape Hatches](https://cdk8s.io/docs/latest/concepts/escape-hatches/) to path the deployment resource with everything you need.

**Comment by philschmid** [comment]
Thank you for the response @iliapolo! 
I will take a look and see if and when i could work on this.
