### ISSUE TITLE
Secret volume support

### ISSUE THREAD

**Issue by plaisted** [cdk8s-team/cdk8s-plus#34]
I could be missing something but don't see a way to use secret volumes with this library.

The `Volume` class has a protected constructor and only supports config maps and empty directories.

The `Deployment` and `Container` classes require modifications to pass through methods that only accept the `Volume` class.

Is this not supported right now? 

As a side note it would be useful to have some advanced access to cover areas not implemented by the high level abstractions, something like the following for this use case: 
```typescript
Volume.create({ name: "secret", secret: { secretName: "secret-name" } } as k8.Volume) // create volume from raw kubernetes spec
```

**Comment by iliapolo** [comment]
Keep
