### ISSUE TITLE
Add support for Kubernetes `v1.30.0`

### ISSUE THREAD

**Issue by DaxServer** [cdk8s-team/cdk8s-plus#4137]
### Description of the feature or enhancement:
Add support for Kubernetes `v1.30.0`

### Use Case:
This would integrate the K8s latest release with cdk8s+

### Other:
* [ ] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
All done
