### ISSUE TITLE
cdk8s-plus Ingress uses `onValidate()`, which isn't allowed in the latest `constructs`

### ISSUE THREAD

**Issue by dancmeyers** [cdk8s-team/cdk8s-plus#492]
I'm attempting to upgrade from CDK8s 1.5.28 to 2.2.50, having previously upgraded from CDK 1.x to 2.x, using `constructs` 10.0.74. When I attempt to deploy my Ingress I get the error

```
the construct "<INGRESS_LOGICAL_ID>" has a "onValidate()" method which is no longer supported. Use "construct.node.addValidation()" to add validations to a construct
```

I can see that this method exists in the `Ingress` construct on cdk8s-plus, here: https://github.com/cdk8s-team/cdk8s-plus/blob/da892bc7ae08531a2b85372c28d8b3163e350bcb/src/ingress.ts#L107-L112

This means that cdk8s-plus is not compatible with the latest releases of the `constructs` library. If I comment out my ingress definitions my CDK app sythensises correctly. The CDK RFC about this change I found at https://github.com/aws/aws-cdk-rfcs/blob/master/text/0192-remove-constructs-compat.md#08-validation-the-validate-hook-is-now-nodeaddvalidation.

**Comment by iliapolo** [comment]
@dancmeyers The latest release candidates in the 2.x version line resolved this. You should be able to use them now. 

https://www.npmjs.com/package/cdk8s-plus-24
