### ISSUE TITLE
Move cdk8s+ docs to cdk8s-plus repo

### ISSUE THREAD

**Issue by Chriscbr** [cdk8s-team/cdk8s-plus#493]
The cdk8s-plus [docs](https://github.com/cdk8s-team/cdk8s/tree/master/docs/plus) from the website need to live in this repository because they change whenever we push changes to cdk8s-plus. 

We need the build script of the website to consume them from the published cdk8s-plus-X libraries, just like we do for api references. Ideally, we would also create a separate tab for each cdk8s-plus-X library in the website, and not display only the latest.

**Comment by iliapolo** [comment]
Resolved by https://github.com/cdk8s-team/cdk8s-plus/pull/1224
