### ISSUE TITLE
Create Destination Rule Yaml

### ISSUE THREAD

**Issue by rohitranjan1991** [cdk8s-team/cdk8s-plus#531]
Thanks for this awesome library. How do I create Destination Rule and Virtual Service Yaml from this library?

**Comment by Chriscbr** [comment]
Hi @rohitranjan1991! I believe Destination Rule and Virtual Service are both Istio resources (not core Kubernetes resources) so to use them you would need to obtain the Custom Resource Definition for Istio and then import them into cdk8s using the import command. See our docs [here](https://cdk8s.io/docs/latest/cli/import/#crds) for more information. Let me know if this helps. 🙂

**Comment by rohitranjan1991** [comment]
@Chriscbr Thanks for a quick reply :-). I am fetting the below error when i am trying to create imports for Virtual Service Istio:

```
➜  hello kubectl get crd virtualservices.networking.istio.io -o json | cdk8s import /dev/stdin
Importing resources, this may take a few moments...
networking.istio.io
  networking.istio.io/virtualservice
NOTE: Temp directory retained due to an error: /var/folders/y4/39vlr3g51fl41jglsklh32xc0000gn/T/temp-6AU9Sh
Error: jsii compilation failed with non-zero exit code: 1
  | [2022-04-08T13:27:17.341] [ERROR] jsii/compiler - Compilation errors prevented the JSII assembly from being created
  | warning JSII6: A "peerDependency" on "constructs" at "3.3.259" means you should take a "devDependency" on "constructs" at "3.3.259" (found "undefined")"
  | warning JSII6: A "peerDependency" on "cdk8s" at "1.5.62" means you should take a "devDependency" on "cdk8s" at "1.5.62" (found "undefined")"
  | warning JSII3: There is no "README.md" file. It is required in order to generate valid PyPI (Python) packages.
  | io.istio.networking.ts:218:12 - error TS2300: Duplicate identifier 'mirrorPercent'.
  | 218   readonly mirrorPercent?: number;
  |                ~~~~~~~~~~~~~
  | io.istio.networking.ts:232:12 - error TS2300: Duplicate identifier 'mirrorPercent'.
  | 232   readonly mirrorPercent?: number;
  |                ~~~~~~~~~~~~~
  +----------------------------------------------------------------------------------
  | Command: /usr/local/Cellar/cdk8s/1.0.143/libexec/lib/node_modules/cdk8s-cli/node_modules/jsii/bin/jsii --silence-warnings reserved-word
  | Workdir: /var/folders/y4/39vlr3g51fl41jglsklh32xc0000gn/T/temp-6AU9Sh
  +----------------------------------------------------------------------------------
    at newError (/usr/local/Cellar/cdk8s/1.0.143/libexec/lib/node_modules/cdk8s-cli/node_modules/jsii-srcmak/lib/util.js:62:20)
    at ChildProcess.<anonymous> (/usr/local/Cellar/cdk8s/1.0.143/libexec/lib/node_modules/cdk8s-cli/node_modules/jsii-srcmak/lib/util.js:79:29)
    at Object.onceWrapper (node:events:642:26)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
➜  hello
```

This is the CRD's json output: [here](https://pastebin.com/wgueB4Zw)

Any Idea what i could be doing wrong here.

**Comment by rohitranjan1991** [comment]
If i remove the "mirror_percent" key from both the versions of Virtual Service, then it is working. But thats a manual edit to the crds, is there any way to workaround this via the cdk8s cli.

**Comment by Chriscbr** [comment]
Hi @rohitranjan1991 - I believe this is a known bug reported here: https://github.com/cdk8s-team/cdk8s/issues/2158. If you could give a +1 (👍 ) to help us prioritize the bug that would be greatly appreciated! (Pull requests are also welcome)

I'm closing this issue since it doesn't seem to be related to cdk8s-plus, but if you have other issues with [cdk8s-plus](https://github.com/cdk8s-team/cdk8s-plus) or [cdk8s](https://github.com/cdk8s-team/cdk8s), or have ideas for features you would like, don't hesitate to create a new issue in the respective repository. 🙂
