### ISSUE TITLE
Python, deployment select issue

### ISSUE THREAD

**Issue by bjarneo** [cdk8s-team/cdk8s-plus#745]
👋 

I am using the python client with version `2.0.0b15`, and I am having issues when it comes to the select command on the deployment object.

code:
```python
deployment.select(LabelSelector.of({"labels": {"app": "my-app"}}))
```

error message
```
raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Expected object reference, got {"$jsii.map":{"labels":{"$jsii.map":{"app":"my-app"}}}}
```

I can't really find any documentation for this (as the documentation is not up to date), so I am trying to read the source code after I downloaded the package from pypi, and the tests written in typescript.

Approach from the tests
```js
  const expectedSelector = { foo: 'bar' };

  deployment.select(kplus.LabelSelector.of({ labels: { foo: expectedSelector.foo } }));
```

Any indications of what I am doing wrong here?

This is how the jsii python code looks for the package:
```python
class LabelSelector(metaclass=jsii.JSIIMeta, jsii_type="cdk8s-plus-22.LabelSelector"):
    '''Match a resource by labels.'''

    @jsii.member(jsii_name="of") # type: ignore[misc]
    @builtins.classmethod
    def of(
        cls,
        options: typing.Optional["LabelSelectorOptions"] = None,
    ) -> "LabelSelector":
        '''
        :param options: -
        '''
        return typing.cast("LabelSelector", jsii.sinvoke(cls, "of", [options]))
```

**Comment by Chriscbr** [comment]
Oof, that unusual. Thanks for reporting the bug @bjarneo.

For anyone else's context, this is the relevant source code from the original TypeScript:

<details>

```ts
/**
 * Options for `LabelSelector.of`.
 */
export class LabelSelectorOptions {

  /**
   * Strict label matchers.
   */
  readonly labels?: { [key: string]: string };

  /**
   * Expression based label matchers.
   */
  readonly expressions?: LabelExpression[];
}

/**
 * Match a resource by labels.
 */
export class LabelSelector {

  public static of(options: LabelSelectorOptions = {}) {
    return new LabelSelector(options.expressions ?? [], options.labels ?? {});
  }

  private constructor(
    private readonly expressions: LabelExpression[],
    private readonly labels: { [key: string]: string }) {}
}
```

</details>

I was also able to reproduce this error... I was also able to get it compiling if I try instantiating an empty "LabelSelectorOptions" class, but anything more causes it to fail.

```
deployment.select(kplus.LabelSelector.of(
    options=kplus.LabelSelectorOptions()
))
```

I think this is an issue with the bindings generated by [jsii](https://github.com/aws/jsii/). This might require some further debugging...

**Comment by bjarneo** [comment]
Thank you for your reply.

Yes, was able to do the same with the `LabelSelectorOptions` as well. I am feeling more sane now as this most likely is an issue with the binding. 😅
