### ISSUE TITLE
Configure default value for `securityContext.privileged`

### ISSUE THREAD

**Issue by iliapolo** [cdk8s-team/cdk8s-plus#809]
Should be set to `false`.

### Additional resources

- https://polaris.docs.fairwinds.com/checks/security/
- https://github.com/zegl/kube-score/blob/master/README_CHECKS.md
- https://hub.datree.io/built-in-rules/prevent-privileged-containers

**Comment by vinayak-kukreja** [comment]
I believe this is already covered [here](https://github.com/cdk8s-team/cdk8s-plus/blob/k8s-24/main/src/container.ts#L67).
