### ISSUE TITLE
Configure default `automountServiceAccountToken` in pods and service accounts

### ISSUE THREAD

**Issue by iliapolo** [cdk8s-team/cdk8s-plus#818]
Should be set to `false`.

### Additional resources

- https://hub.datree.io/built-in-rules/prevent-service-account-token-auto-mount

**Comment by vinayak-kukreja** [comment]
I see this is already implemented, 🚀 
* [Pods](https://github.com/cdk8s-team/cdk8s-plus/blob/k8s-24/main/src/pod.ts#L38)
* [ServiceAccounts](https://github.com/cdk8s-team/cdk8s-plus/blob/k8s-24/main/src/service-account.ts#L104)
