### ISSUE TITLE
Configure default image pull policy on containers 

### ISSUE THREAD

**Issue by iliapolo** [cdk8s-team/cdk8s-plus#820]
Should be set to `Always`.

### Additional resources

- https://github.com/zegl/kube-score/blob/master/README_CHECKS.md

**Comment by vinayak-kukreja** [comment]
I believe this is already done [here](https://github.com/cdk8s-team/cdk8s-plus/blob/k8s-24/main/src/container.ts#L742)

**Comment by iliapolo** [comment]
Yeap this is done
