### ISSUE TITLE
Releases showing duplicate information

### ISSUE THREAD

**Issue by Chriscbr** [cdk8s-team/cdk8s-plus#83]
There seems to be an issue with the projen release mechanism, causing releases to show more changes than they actually include. See for example how two cdk8s-plus-22 releases immediately after each other include the same changes:

https://github.com/cdk8s-team/cdk8s-plus/releases/tag/cdk8s-plus-22%2Fv1.0.0-beta.20
https://github.com/cdk8s-team/cdk8s-plus/releases/tag/cdk8s-plus-22%2Fv1.0.0-beta.21

**Comment by Chriscbr** [comment]
May be fixed by https://github.com/projen/projen/pull/1661

**Comment by iliapolo** [comment]
Yeap, resolved by https://github.com/projen/projen/pull/1661
