### ISSUE TITLE
Namespace not passed down (Deployment -> ExposeViaService)

### ISSUE THREAD

**Issue by jaskerv** [cdk8s-team/cdk8s-plus#881]
*Issue transferred from https://github.com/cdk8s-team/cdk8s-plus-go*

----------------------------------------------------------------------------

I've configured my deployment to be in a specific namespace. I'm attempting to expose the deployment with `ExposeViaService`.

After running `synth`, the Service is lacking the namespace metadata. I'm not sure if this is meant to be passed down by deployment or if I would have to configure it manually (which I can't seem to find how).

**Comment by iliapolo** [comment]
@Jaskerv thanks for reporting. Indeed its' a bug. 

While we work on a fix, here is a workaround you can use:

```ts
const deployment = ...
const service = deployment.exposeViaService();
ApiObject.of(service).addJsonPatch(JsonPatch.add('/metadata', { namespace: deployment.metadata.namespace }));
```

**Comment by jaskerv** [comment]
@iliapolo awesome thanks.

Would you be able to give me a go workaround?

Currently trying this 
```
patch := struct {
		namespace *string
	}{
		namespace: deployment.Metadata().Namespace(),
	}
service.ApiObject().AddJsonPatch(cdk8s.JsonPatch_Add(jsii.String("/metadata"), patch))
```

but with no success

EDIT:
this worked

```
patch = map[string]*string{
"name":      servicePort.Name(),
"namespace": deployment.Metadata().Namespace(),
}
servicePort.ApiObject().AddJsonPatch(cdk8s.JsonPatch_Add(jsii.String("/metadata"), patch))
```

It seems `cdk8s.JsonPatch_Add` replaces the entire object rather than merging/overwriting it 🤔 its removing `name` in metadata

**Comment by iliapolo** [comment]
@Jaskerv You should be able to use the new release now: https://github.com/cdk8s-team/cdk8s-plus-go/releases/tag/cdk8splus24%2Fv2.0.0-rc.36

**Comment by jaskerv** [comment]
Thanks!
